import Box from '@mui/material/Box';
import Container from '@mui/material/Container';
import Stack from '@mui/material/Stack';
import Typography from '@mui/material/Typography';

const YEAR = new Date().getFullYear();

export function SiteFooter() {
  return (
    <Box component="footer" sx={{ borderTop: '1px solid', borderColor: 'divider', mt: 'auto' }}>
      <Container maxWidth="lg" sx={{ py: 5, px: { xs: 3, sm: 4, md: 6, lg: 8 } }}>
        <Stack
          direction={{ xs: 'column', sm: 'row' }}
          justifyContent="space-between"
          alignItems={{ xs: 'flex-start', sm: 'center' }}
          spacing={2}
        >
          <Typography
            variant="caption"
            sx={{
              color: 'text.secondary',
              fontFamily: 'var(--font-jetbrains)',
              textTransform: 'uppercase',
              letterSpacing: '0.08em',
              fontSize: 11,
            }}
          >
            © {YEAR} Desko · tool interno · ad uso esclusivo dei dipendenti
          </Typography>
          <Typography
            variant="caption"
            sx={{
              color: 'text.secondary',
              fontFamily: 'var(--font-jetbrains)',
              textTransform: 'uppercase',
              letterSpacing: '0.08em',
              fontSize: 11,
            }}
          >
            generated by design-md-to-app from .workflow/DESIGN.md
          </Typography>
        </Stack>
      </Container>
    </Box>
  );
}
